/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria.View.SubtelasPedido;

import Enum.PizzasEnum;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pizzaria.Controller.ControllerCobertura;
import pizzaria.Controller.ControllerPedido;
import pizzaria.Controller.ControllerPedidoPizza;
import pizzaria.Interfaces.Frame.IFrameCobertura;
import pizzaria.Interfaces.Frame.IFrameConsultaPedido;
import pizzaria.Interfaces.Frame.IFramePizzaRelacionadaPedido;
import pizzaria.Interfaces.Frame.Observador;
import pizzaria.Model.TableModel.TablePizzasPedido;
import readOnly.PizzaReadOnlyPedido;

/**
 *
 * @author Pichau
 */
public class FrameMostraPizzasDoPedido extends javax.swing.JFrame implements Observador, IFrameCobertura, IFrameConsultaPedido, IFramePizzaRelacionadaPedido {

    /**
     * Creates new form FrameMostraPizzasDoPedido
     */
    private TablePizzasPedido tpp;
    private ControllerPedidoPizza controllerPedidoPizza;
    private ControllerPedido controllerPedido;
    private IFrameConsultaPedido pedido;
    private int idPedido;
    private Observador obs;

    public FrameMostraPizzasDoPedido() {
    }

    public FrameMostraPizzasDoPedido(IFrameConsultaPedido pedido, Observador obs) {
        initComponents();

        tbPizzas.setRowHeight(25);

        tpp = new TablePizzasPedido();
        controllerPedido = new ControllerPedido();
        controllerPedidoPizza = new ControllerPedidoPizza();

        idPedido = pedido.getIdPedido();
        this.pedido = pedido;
        this.obs = obs;

        carregarNaTabela();
        lblValorTotal.setText(String.valueOf(pedido.getValorTotal()));
    }

    private void carregarNaTabela() {
        tbPizzas.removeAll();
        controllerPedidoPizza.pegar(idPedido).forEach(
                c -> tpp.addRow(new Object[]{c.getPizza().getId(), c.getPedido(),
            c.getCobertura().getId(), c.getPizza().getSabor(), c.getId(),
            c.getPizza().getQuantidade(), c.getPizza().getTipoPizza().name()
        }));

        tbPizzas.setModel(tpp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMain6 = new javax.swing.JPanel();
        btnSair6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblEnderecoSelecionadoNoPedido6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPizzas = new javax.swing.JTable();
        btnMinimizar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnAlterarPizzaPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnMain6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSair6.setBackground(new java.awt.Color(255, 255, 255));
        btnSair6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSair6.setText("X");
        btnSair6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSair6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair6btnSairActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Pizzas Do Pedido");

        lblEnderecoSelecionadoNoPedido6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tbPizzas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbPizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPizzasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPizzas);

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnMinimizar.setText("_");
        btnMinimizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarbtnSairActionPerformed(evt);
            }
        });

        btnRetirar.setBackground(new java.awt.Color(255, 255, 255));
        btnRetirar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRetirar.setText("Retirar Pizza");
        btnRetirar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirar.setEnabled(false);
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarbtnSairActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label3.setText("Pizzas Do Pedido");

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAlterarPizzaPedido.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarPizzaPedido.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAlterarPizzaPedido.setText("Aterar Pizza Pedido");
        btnAlterarPizzaPedido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAlterarPizzaPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarPizzaPedido.setEnabled(false);
        btnAlterarPizzaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPizzaPedidobtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMain6Layout = new javax.swing.GroupLayout(pnMain6);
        pnMain6.setLayout(pnMain6Layout);
        pnMain6Layout.setHorizontalGroup(
            pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMain6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMain6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(pnMain6Layout.createSequentialGroup()
                        .addGroup(pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMain6Layout.createSequentialGroup()
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterarPizzaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnMain6Layout.createSequentialGroup()
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorTotal))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnMain6Layout.createSequentialGroup()
                                .addGap(599, 599, 599)
                                .addComponent(lblEnderecoSelecionadoNoPedido6)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        pnMain6Layout.setVerticalGroup(
            pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMain6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSair6)
                        .addComponent(btnMinimizar)))
                .addGap(18, 18, 18)
                .addComponent(lblEnderecoSelecionadoNoPedido6)
                .addGap(32, 32, 32)
                .addGroup(pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarPizzaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnMain6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(lblValorTotal))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSair6btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair6btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSair6btnSairActionPerformed

    private void btnMinimizarbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarbtnSairActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarbtnSairActionPerformed

    private void btnRetirarbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarbtnSairActionPerformed
        if (tbPizzas.getRowCount() <= 1) {
            JOptionPane.showMessageDialog(null, "Não possível excluir esse item, pois ele é o unico na tabela!");
        } else {
            configurarDeletar();
        }
    }//GEN-LAST:event_btnRetirarbtnSairActionPerformed

    private void configurarDeletar() throws HeadlessException {
        try {
            deletarItem();

            atualizarValorFinal();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void atualizarValorFinal() {
        controllerPedido.atualizarPelaPizza(this);
        obs.setObservador();
    }

    private void atualizarTabela() {
        carregarNaTabela();
    }

    private void deletarItem() throws NumberFormatException {
        controllerPedidoPizza.deletarItem(this);
    }

    private void tbPizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPizzasMouseClicked
        btnRetirar.setEnabled(true);
        btnAlterarPizzaPedido.setEnabled(true);
    }//GEN-LAST:event_tbPizzasMouseClicked

    private void btnAlterarPizzaPedidobtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPizzaPedidobtnSairActionPerformed
        new FrameAlterar(controllerPedidoPizza, this, this).setVisible(true);
    }//GEN-LAST:event_btnAlterarPizzaPedidobtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMostraPizzasDoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMostraPizzasDoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMostraPizzasDoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMostraPizzasDoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameMostraPizzasDoPedido().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPizzaPedido;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnSair6;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lblEnderecoSelecionadoNoPedido6;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnMain6;
    private javax.swing.JTable tbPizzas;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getIdPedido() {
        return pedido.getIdPedido();
    }

    @Override
    public int getIdEndereco() {
        return pedido.getIdEndereco();
    }

    @Override
    public BigDecimal getValorTotal() {
        return controllerPedido.pegarUnico(pedido.getIdPedido()).getValorTotal();
    }

    @Override
    public boolean isPronto() {
        return pedido.isPronto();
    }
    
    public String pegarValor(int coluna){
        return tpp.getValueAt(tbPizzas.getSelectedRow(), coluna).toString();
    }

    @Override
    public int getQuantidade() {
        return Integer.parseInt(pegarValor(5));
    }

    @Override
    public int getIdPizza() {
        return Integer.parseInt(pegarValor(0));
    }

    @Override
    public PizzasEnum getTipoPizza() {
        return PizzasEnum.valueOf(pegarValor(6));
    }

    @Override
    public String getSabor() {
        return pegarValor(3);
    }

    @Override
    public BigDecimal getValor() {
        return controllerPedidoPizza.pegarUnico(getIdPedidoPizzas()).getPizza().getValor();
    }

    @Override
    public int getIdPedidoPizzas() {
        return Integer.parseInt(pegarValor(4));
    }

    @Override
    public IFrameCobertura getCobertura() {
        return this;
    }

    @Override
    public ArrayList<PizzaReadOnlyPedido> getPizzasDoModelo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getIdCobertura() {
        return Integer.parseInt(pegarValor(2));
    }

    @Override
    public String getNomeCobertura() {
        return new ControllerCobertura().pegarUnico(getIdCobertura()).getNome();
    }

    @Override
    public BigDecimal getValorCobertura() {
        return new ControllerCobertura().pegarUnico(getIdCobertura()).getValor(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setObservador() {
        this.atualizarTabela();
    }

    @Override
    public int getIdCoberturaRelacionada() {
        return getIdCobertura();
    }
}
