/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria.View;

import Enum.PizzasEnum;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import pizzaria.Controller.ControllerPizza;
import pizzaria.Interfaces.Frame.IFrameCadastroPizza;
import pizzaria.Interfaces.Frame.IFramePizza;
import pizzaria.Interfaces.IJlist;
import pizzaria.View.Util.ConfigurarJScroll;
import pizzaria.View.Util.GerenciaLista.UtilListaCadastroPizza;
import pizzaria.View.Util.Utilidade;

/**
 *
 * @author Guilh
 */
public class FrameCadastroPizza extends javax.swing.JPanel implements IFramePizza, IFrameCadastroPizza, IJlist {

    /**
     * Creates new form FrameCadastroPizza
     */
    protected ControllerPizza controllerPizza;
    protected DefaultListModel listModel = new DefaultListModel();
    private ArrayList<PizzasEnum> pizzas;
    private String tipoPizza;
    protected UtilListaCadastroPizza controllerLista;

    public FrameCadastroPizza() {
        initComponents();
        controllerPizza = new ControllerPizza();
        txtCodigoPizza.setText(Utilidade.TextoChave(controllerPizza));
        pizzas = new ArrayList<>();

        controllerLista = new UtilListaCadastroPizza(this);
        lstPizzas.setModel(listModel);
        ConfigurarJScroll.configJscrollPane(jScrollPane1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPizzas = new javax.swing.JList<>();
        PnMain = new javax.swing.JPanel();
        txtSabor = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoPizza = new javax.swing.JTextField();
        pnTipoPizza = new javax.swing.JPanel();
        chkIndividual = new javax.swing.JCheckBox();
        chkRegular = new javax.swing.JCheckBox();
        chkFamiliar = new javax.swing.JCheckBox();
        btnRetirar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(760, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 110, 45));

        lstPizzas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstPizzas.setToolTipText("Pressione CTRL e clique com o botão direito do mouse para ir selecionando.");
        lstPizzas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPizzasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPizzas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 100, 270, 220));

        PnMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PnMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSabor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PnMain.add(txtSabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 29));

        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PnMain.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 270, 29));

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        PnMain.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 270, 45));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");
        PnMain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sabor:");
        PnMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Código da Pizza:");
        PnMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Pizza:");
        PnMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 141, -1));

        txtCodigoPizza.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigoPizza.setEnabled(false);
        PnMain.add(txtCodigoPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 29));

        chkIndividual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkIndividual.setSelected(true);
        chkIndividual.setText("Individual");
        chkIndividual.setEnabled(false);
        pnTipoPizza.add(chkIndividual);

        chkRegular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkRegular.setText("Regular");
        chkRegular.setToolTipText("");
        pnTipoPizza.add(chkRegular);

        chkFamiliar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkFamiliar.setText("Familiar");
        chkFamiliar.setToolTipText("");
        pnTipoPizza.add(chkFamiliar);

        PnMain.add(pnTipoPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 160, 70));

        add(PnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 330, 380));

        btnRetirar.setBackground(new java.awt.Color(255, 255, 255));
        btnRetirar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRetirar.setEnabled(false);
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 110, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Lista com as pizzas a serem cadastradas.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (Utilidade.VerificarCamposVazios(this.PnMain)) {
            return;
        }
        controllerLista.AdicionarList(this);
        pizzas.clear();

        enableCadastrarButton();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (lstPizzas.getModel().getSize() == 0) {
            JOptionPane.showMessageDialog(null, "Não existe nada na lista!");
            return;
        }
        if (!lstPizzas.isSelectionEmpty()) {
            CadastrarSelecionados();
        } else {
            CadastrarTodos();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void CadastrarSelecionados() {
        Utilidade.ProcurarCheckBoxTipoPizza(pnTipoPizza).forEach((String c) -> {
            controllerPizza.adicionar(this);
        });
    }

    private void CadastrarTodos() {
        int valor = Utilidade.CriarOpcao("Deseja cadastrar tudo ?");

        if (valor == 0) {
            controllerPizza.adicionarTodosPro(new UtilListaCadastroPizza(this)
                    .PegarTodosElementos());
        }
    }

    private void enableCadastrarButton() {
        if ((this.lstPizzas.getLastVisibleIndex() + 1) > 0) {
            this.btnCadastrar.setEnabled(true);
            this.btnRetirar.setEnabled(true);
        }
    }

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        controllerLista.retirarSelecionados();
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void lstPizzasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPizzasValueChanged

    }//GEN-LAST:event_lstPizzasValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnMain;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JCheckBox chkFamiliar;
    private javax.swing.JCheckBox chkIndividual;
    private javax.swing.JCheckBox chkRegular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPizzas;
    private javax.swing.JPanel pnTipoPizza;
    private javax.swing.JTextField txtCodigoPizza;
    private javax.swing.JTextField txtSabor;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getIdPizza() {
        return Integer.parseInt(txtCodigoPizza.getText());
    }

    @Override
    public ArrayList<PizzasEnum> getTiposPizza() {
        Utilidade.ProcurarCheckBoxTipoPizza(pnTipoPizza).forEach(c ->
        pizzas.add(PizzasEnum.valueOf(c.trim().toUpperCase())));
        
        return pizzas;
    }

    @Override
    public String getSabor() {
        return txtSabor.getText();
    }

    @Override
    public BigDecimal getValor() {
        return BigDecimal.valueOf(Double.parseDouble(txtValor.getText()));
    }

    @Override
    public DefaultListModel getModelo() {
        return listModel;
    }

    @Override
    public JList getLista() {
        return lstPizzas;
    }

    @Override
    public DefaultListModel getModeloPizzaDoPedido() {
        return null;
    }

    @Override
    public JList getListaPizzaDoPedido() {
        return null;
    }

    @Override
    public PizzasEnum getTipoPizza() {
        return PizzasEnum.valueOf(tipoPizza.trim().toUpperCase());
    }
    
    @Override 
    public void percorrerTipo(String tipo){
        this.tipoPizza = tipo;
    }
}
