/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria.View;

import java.awt.HeadlessException;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import pizzaria.Controller.ControllerEndereco;
import pizzaria.Controller.ControllerPedido;
import pizzaria.Interfaces.Frame.IFrameConsultaPedido;
import pizzaria.Interfaces.Frame.Observador;
import pizzaria.Model.TableModel.TablePedido;
import pizzaria.View.SubtelasPedido.FrameAlterar;
import pizzaria.View.SubtelasPedido.FrameMostraPizzasDoPedido;
import pizzaria.View.Util.ConfiguraJScroll;

/**
 *
 * @author Pichau
 */
public class FrameConsultaPedidos extends javax.swing.JPanel implements Observador, IFrameConsultaPedido {

    /**
     * Creates new form FrameConsultaPedidos
     */
    private ControllerPedido controllerPedido;
    private TablePedido tbp;
    private TablePedido tbpPesquisa;

    public FrameConsultaPedidos() {
        initComponents();
        controllerPedido = new ControllerPedido();

        ConfiguracaoVisualTabela();
        tbp = new TablePedido();
        tbpPesquisa = new TablePedido();

        ConfigurarTable();
    }

    private void ConfiguracaoVisualTabela() {
        tbPedidos.setRowHeight(25);
        tbPedidos.setBorder(BorderFactory.createEmptyBorder());
        ConfiguraJScroll.configJscrollPane(jScrollPane1);
    }

    private void ConfigurarTable() {
        AtualizarTable();
        try {
            controllerPedido.pegarVarios().forEach(c -> tbp.addRow(
                    new Object[]{c.getId(), c.getEndereco().getId(), c.getValorTotal(), c.getStatus()}
            ));
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível abrur a tabela! \nMotivo:" + ex.getMessage());
        }

        tbPedidos.setModel(tbp);
    }

    private void ConfigurarTablePesquisa(int id) {
        VerificarValoresNumericos();
        AtualizarTable();

        try {
            controllerPedido.pegar(id).forEach(c -> tbpPesquisa.addRow(
                    new Object[]{c.getId(), c.getEndereco().getId(), c.getValorTotal(), c.getStatus()}
            ));

            tbPedidos.setModel(tbpPesquisa);

        } catch (RuntimeException ex) {
            txtId.setText("");
            ConfigurarTable();
        }
    }

    private void VerificarValoresNumericos() throws NumberFormatException {
        boolean numero = txtId.getText().chars().anyMatch(c -> !(Character.isDigit(c)));

        if (numero) {
            throw new NumberFormatException("Valores não númericos, não são aceitos!");
        }
    }

    private void ConfigurarTablePesquisa(boolean estado) {
        AtualizarTable();

        controllerPedido.pegar(estado).forEach(c -> tbpPesquisa.addRow(
                new Object[]{c.getId(), c.getEndereco().getId(),
                    c.getValorTotal(), c.getStatus()}
        ));
        tbPedidos.setModel(tbpPesquisa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGrupoStatus = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnPesquisa = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdbStatusVerdadeiro = new javax.swing.JRadioButton();
        rdbStatusFalso = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rdbTodos = new javax.swing.JRadioButton();
        pnDados = new javax.swing.JPanel();
        lblIDPedido = new javax.swing.JLabel();
        lblFeito = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblIdEndereco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnAcoesGrid = new javax.swing.JPanel();
        btnPizzaDoPedido = new javax.swing.JButton();
        btnDefinirFeito = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(940, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPedidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Codigo Pedido", "Já foi entregue ?", "Codigo do Endereço", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPedidos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 660, 310));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Dado Selecionado:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 240, -1));

        pnPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnPesquisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setBorder(null);
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        pnPesquisa.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 178, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Procurar pelo ID:");
        pnPesquisa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        bgGrupoStatus.add(rdbStatusVerdadeiro);
        rdbStatusVerdadeiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbStatusVerdadeiro.setText("Feito");
        rdbStatusVerdadeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbStatusVerdadeiroActionPerformed(evt);
            }
        });
        pnPesquisa.add(rdbStatusVerdadeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        bgGrupoStatus.add(rdbStatusFalso);
        rdbStatusFalso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbStatusFalso.setSelected(true);
        rdbStatusFalso.setText("Não Feito");
        rdbStatusFalso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbStatusFalsoActionPerformed(evt);
            }
        });
        pnPesquisa.add(rdbStatusFalso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Procurar por pedidos feitos:");
        pnPesquisa.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        bgGrupoStatus.add(rdbTodos);
        rdbTodos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbTodos.setText("Todos");
        rdbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTodosActionPerformed(evt);
            }
        });
        pnPesquisa.add(rdbTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        add(pnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 420, 100));

        pnDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIDPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnDados.add(lblIDPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblFeito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnDados.add(lblFeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnDados.add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        lblIdEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnDados.add(lblIdEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        add(pnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 450, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Consulta pedidos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 26, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Pesquisa:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pnAcoesGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPizzaDoPedido.setBackground(new java.awt.Color(255, 255, 255));
        btnPizzaDoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPizzaDoPedido.setText("Verificar Pizzas do pedido");
        btnPizzaDoPedido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnPizzaDoPedido.setEnabled(false);
        btnPizzaDoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaDoPedidoActionPerformed(evt);
            }
        });

        btnDefinirFeito.setBackground(new java.awt.Color(255, 255, 255));
        btnDefinirFeito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDefinirFeito.setText("Alterar estado para Feito");
        btnDefinirFeito.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDefinirFeito.setEnabled(false);
        btnDefinirFeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirFeitoActionPerformed(evt);
            }
        });

        btnAlterarProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterarProduto.setText("Alterar Endereço do Pedido");
        btnAlterarProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAlterarProduto.setEnabled(false);
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAcoesGridLayout = new javax.swing.GroupLayout(pnAcoesGrid);
        pnAcoesGrid.setLayout(pnAcoesGridLayout);
        pnAcoesGridLayout.setHorizontalGroup(
            pnAcoesGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAcoesGridLayout.createSequentialGroup()
                .addGroup(pnAcoesGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAcoesGridLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPizzaDoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAcoesGridLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnDefinirFeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnAcoesGridLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAlterarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnAcoesGridLayout.setVerticalGroup(
            pnAcoesGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAcoesGridLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnDefinirFeito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPizzaDoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(pnAcoesGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 220, 270));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ações com a linha do Grid:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        ColocandoPesquisaNaTabela();
    }//GEN-LAST:event_txtIdFocusGained

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed

    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost

    }//GEN-LAST:event_txtIdFocusLost

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if (evt.getKeyCode() == 10) {
            ColocandoPesquisaNaTabela();
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void rdbStatusVerdadeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbStatusVerdadeiroActionPerformed
        ConfigurarTablePesquisa(true);
    }//GEN-LAST:event_rdbStatusVerdadeiroActionPerformed

    private void rdbStatusFalsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbStatusFalsoActionPerformed
        ConfigurarTablePesquisa(false);
    }//GEN-LAST:event_rdbStatusFalsoActionPerformed

    private void btnPizzaDoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaDoPedidoActionPerformed
        try{
            new FrameMostraPizzasDoPedido(this, this).setVisible(true);
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu algo de errado ao chamar as pizzas!");
        }
    }//GEN-LAST:event_btnPizzaDoPedidoActionPerformed

    private void tbPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidosMouseClicked
        try {
            ConfigurarExibicaoSelecionado();
            ConfigurarExibicaoDeAcao();
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_tbPedidosMouseClicked

    private void ConfigurarExibicaoDeAcao() {
        ConfigurarBtnComCondicao(btnDefinirFeito);
        ConfigurarBtnComCondicao(btnAlterarProduto);

        btnPizzaDoPedido.setEnabled(true);
    }

    private void ConfigurarBtnComCondicao(JButton button) {
        button.setEnabled(false);

        if (!isPronto()) {
            button.setEnabled(true);
        }
    }

    private void btnDefinirFeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirFeitoActionPerformed
        controllerPedido.atualizarEstado(this);
        btnAlterarProduto.setEnabled(false);
        pegarModelo().updateCell(true, tbPedidos.getSelectedRow(), 3);
    }//GEN-LAST:event_btnDefinirFeitoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        FrameAlterar fa = new FrameAlterar(new ControllerEndereco(), this, this);
        fa.setVisible(true);
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void rdbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTodosActionPerformed
        this.ConfigurarTable();
    }//GEN-LAST:event_rdbTodosActionPerformed

    private void ColocandoPesquisaNaTabela() throws HeadlessException {
        if (!(txtId.getText().isEmpty())) {
            try {
                ConfigurarTablePesquisa(Integer.parseInt(txtId.getText()));
            } catch (NumberFormatException ex) {
                txtId.setText("");
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            ConfigurarTable();
        }
    }

    private void AtualizarTable() {
        tbpPesquisa.deleteAll();
        tbp.deleteAll();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGrupoStatus;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnDefinirFeito;
    private javax.swing.JButton btnPizzaDoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFeito;
    private javax.swing.JLabel lblIDPedido;
    private javax.swing.JLabel lblIdEndereco;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnAcoesGrid;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnPesquisa;
    private javax.swing.JRadioButton rdbStatusFalso;
    private javax.swing.JRadioButton rdbStatusVerdadeiro;
    private javax.swing.JRadioButton rdbTodos;
    private javax.swing.JTable tbPedidos;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    private void ConfigurarExibicaoSelecionado() {
        lblIDPedido.setText("ID do pedido: " + getIdPedido());
        lblFeito.setText("Foi realizado ? " + getFeito());
        lblIdEndereco.setText("ID do endereco: " + getIdEndereco());
        lblValorTotal.setText("Valor total do item: " + getValorTotal());
    }

    private String pegarValor(int coluna) {
        String valor = "";
        try {
            valor = pegarModelo().getValueAt(tbPedidos.getSelectedRow(), coluna).toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você selecionou um item incorreto!\nErro:" + e.getMessage());
        }
        return valor;
    }

    private TablePedido pegarModelo() {
        if (tbp.getRowCount() == 0) {
            return tbpPesquisa;
        }
        return tbp;
    }

    @Override
    public int getIdPedido() {
        return Integer.parseInt(pegarValor(0));
    }

    public String getFeito() {
        return pegarValor(3);
    }

    @Override
    public int getIdEndereco() {
        return Integer.parseInt(pegarValor(1));
    }

    @Override
    public BigDecimal getValorTotal() {
        return BigDecimal.valueOf(Double.parseDouble(pegarValor(2)));
    }

    @Override
    public boolean isPronto() {
        return this.lblFeito.getText().contains("true");
    }

    @Override
    public void setObservador() {
        AtualizarTable();
        ConfigurarTable();
    }
}
