/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria.View;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import pizzaria.Controller.ControllerEndereco;
import pizzaria.Interfaces.Frame.IFrameConsultaEndereco;
import pizzaria.View.Util.Utilidade;
import readOnly.EnderecoReadOnly;

/**
 *
 * @author Guilh
 */
public class FrameCadastroEndereco extends javax.swing.JPanel implements IFrameConsultaEndereco {

    /**
     * Creates new form FrameCadastroEndereco
     */
    public FrameCadastroEndereco() {
        initComponents();
        txtId.setText(Utilidade.TextoChave(new ControllerEndereco()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMainEndereco = new javax.swing.JPanel();
        txtBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        pnMainEndereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnMainEndereco.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Logradouro:");
        pnMainEndereco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Bairro:");
        pnMainEndereco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Código do Enreço:");
        pnMainEndereco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnMainEndereco.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cidade:");
        pnMainEndereco.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtId.setEnabled(false);
        pnMainEndereco.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 29));

        txtLogradouro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnMainEndereco.add(txtLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 32));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        pnMainEndereco.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMainEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMainEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(Utilidade.VerificarCamposVazios(pnMainEndereco)){
            JOptionPane.showMessageDialog(null, "Existe campos Vazios");
            return;
        }
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cadastrar() throws NumberFormatException, HeadlessException {
        new ControllerEndereco().adicionar(this);
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnMainEndereco;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogradouro;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getId() {
        return Integer.parseInt(txtId.getText());
    }

    @Override
    public String getLogradouro() {
        return this.txtLogradouro.getText();
    }

    @Override
    public String getBairro() {
        return txtBairro.getText();
    }

    @Override
    public String getCidade() {
        return txtCidade.getText();
    }
}
